### PR TITLE
Testb

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by rickardnorlander** [comment]
#### :ballot_box_with_check: Voting procedure reminder:

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

_NOTE: the PR will be closed if any new commits are added after:_ 13e81d5d15a7608e6c83d36e9656d54385466449

**Comment by rickardnorlander** [comment]
#### :warning: This PR has been modified so voting will now restart.

**Comment by rickardnorlander** [comment]
:+1:

**Comment by rickardnorlander** [comment]
#### :warning: This PR has been modified so voting will now restart.

**Comment by korczis** [comment]
:+1:

**Comment by mappum** [comment]
:-1:

**Comment by SamsPepper1** [comment]
:+1:

**Comment by dos1** [comment]
I especially love the asdfasdffffff part :+1:

**Comment by rickardnorlander** [comment]
#### :warning: This PR has been modified so voting will now restart.

**Comment by mappum** [comment]
jk it's ok :+1:

**Comment by rickardnorlander** [comment]
#### :warning: This PR has been modified so voting will now restart.

**Comment by rickardnorlander** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **2** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the vote will be restarted if any new commits are added after:* 0e50490d24a3299db86c323e65ce460fc51201aa

**Comment by rickardnorlander** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **2** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the vote will be restarted if any new commits are added after:* 0e50490d24a3299db86c323e65ce460fc51201aa

**Comment by rickardnorlander** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=e44"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 2 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @korczis
 * @SamsPepper1
 * @mappum

**Pull request merged**
